branches:
  only:
  - master
  - scala-2.9
language: scala
jdk:
- openjdk6
scala:
- 2.10.4
script:
- sbt scoverage:test
after_success:
- sbt publish
# https://github.com/scoverage/sbt-coveralls/issues/18
#- sbt coveralls
env:
  global:
    # travis encrypt -r ensime/ensime-server SONATYPE_USERNAME=<USERNAME>
    # travis encrypt -r ensime/ensime-server SONATYPE_PASSWORD=<PASSWORD>
    secure: "SbkeCXHNb4q8gupFzJkx3VL/OKIRZeD+hUAcC7yJb21U4K5u3ZqZuMQJLwab9+at4yTgVmMeF9qyCaxT7Nl8sv6BKcLIxoM94WskUeevogTFKANMVDKj3bvza+mvK5NlNoXRZYZW7Y1Bw/jLSc4+HpeHaaWkLWgsRpPO9IKDhpM="
    secure: "alkJZ1qNKf3kbIIWcP2a5a9hDpD3plCCH8omg62zT0/Il/2EX3Kq+JmGDwy6mAm0vANLeLSY6N9ZGHjlQMWCwDQy12iweL/+Oe2N8qD5PY0kc4jaiwvZowDfLTkhKMWzAm/upSIiqNyXISuZpDxC6ejQqElWkew9CrzI8yp53ws="
